service: vidlabel # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.7
  profile: ${file(../config.${self:provider.stage}.json):vidlabel.profile}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - 'rekognition:*'
      Resource: '*'

    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        Fn::Join:
          - ''
          - - ${self:custom.bucket_arn}
            - '/*'

    - Effect: "Allow"
      Action:
        - iam:GetRole
        - iam:PassRole
      Resource:
        Fn::GetAtt:
          - RekognitionSNSPublishRole
          - Arn

  environment:
      REKOGNITION_SNS_TOPIC_ARN: ${self:custom.rekognitionSNSTopicArn}
      REKOGNITION_ROLE_ARN:
        Fn::GetAtt:
          - RekognitionSNSPublishRole
          - Arn

custom:
  rekognitionSNSTopicArn:
    Fn::Join:
      - ':'
      - - arn
        - aws
        - sns
        - Ref: AWS::Region
        - Ref: AWS::AccountId
        - handle_label_topic

  bucket_arn:
    Fn::Join:
      - ":"
      - - arn
        - aws
        - s3
        - ''
        - ''
        - ${file(../config.${self:provider.stage}.json):vidlabel.bucket}


functions:
  process_video:
    handler: handler.process_video
    events:
      - s3:
          bucket: ${file(../config.${self:provider.stage}.json):vidlabel.bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .mp4
  handle_label:
    handler: handler.handle_label
    events:
      - sns: handle_label_topic


resources:
  Resources:
    RekognitionSNSPublishRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "rekognition.amazonaws.com"
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: RekognitionSNSPublishPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - sns:Publish
                  Resource: ${self:custom.rekognitionSNSTopicArn}
